### ISSUE TITLE
The example is this repo doesn't work as you would expect

### ISSUE THREAD

**Issue by tkrotoff** [christo-pr/dangerously-set-html-content#13]
If you click on the button "Hit here to see magic!" in the example (example/src/App.js) it does NOT work.

This is because DangerouslySetHtmlContent is explicitly coded to render only once:
https://github.com/christo-pr/dangerously-set-html-content/blob/dc7dfd09fe1b5dc87ff65f432b8f8074cb66f62c/src/index.js#L10

**Comment by christo-pr** [comment]
Yeah, you're right I think it no longer works, but seems like the usage of this package has been to render things only once, ever since #7, I haven't heard any issues with this behavior affecting their apps. I guess we can handle that with a new prop probably, I'll look into as soon as I have free time, feel free to send a PR, you're really helping me a lot! Really appreciate it!

**Comment by christo-pr** [comment]
Actually now that you mention, probably this issue is also related: #8

**Comment by christo-pr** [comment]
Thanks for pointing out, I actually made the change, so the latest version (1.1.0) of the lib should include the fix/feature to allow this in case you need, by default it remains as it was all this time 👍
