### ISSUE TITLE
Reactjsv17.0.2 dependency issue

### ISSUE THREAD

**Issue by rash09** [christo-pr/dangerously-set-html-content#14]
Node version:
**v16.20.**

Reactjs version:
**17.0.2**

Error:
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from dangerously-set-html-content@1.1.0
npm ERR! node_modules/dangerously-set-html-content
npm ERR!   dangerously-set-html-content@"*" from the root project

**Comment by christo-pr** [comment]
Hi @rash09 👋🏻 well, the error is pretty much self explanatory, this dependency uses react 18 as peer dependency, we used to have support for react 17, but we no longer have, if you want to use it, I suggest just copy the code and put it manually into your project, otherwise feel free to open a PR to add support for older react versions and I'll review it 👍🏻

**Comment by christo-pr** [comment]
I'll close this since I think the support for older version of React might not be a huge impact for this to work (also not much free time right now to fix it). I think copy/paste the code of the lib should be a fair solution hehehe unless someone raise a PR with the fix 👍
